import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FrontendProvider } from "@/contexts/FrontendContext";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            forcedTheme="light"
            disableTransitionOnChange
          >
        <FrontendProvider>
          {children}
        </FrontendProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
