import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FrontendProvider } from "@/contexts/FrontendContext";
import { ThemeProvider } from "@/components/theme-provider"
import Nav from "@/components/nav/nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            forcedTheme="light"
            disableTransitionOnChange
          >
        <FrontendProvider>
        <div className="fixed top-0 left-0 right-0 h-48 bg-gradient-to-b from-gray-400/30 to-transparent pointer-events-none" />
          {children}
        </FrontendProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
